env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-multi-spaces: "error",
  indent: ["error", 4],
  no-var: "error",
  space-infix-ops: "error",
  func-call-spacing: ["error", "never"],
  semi: ["error", "always"],
  semi-spacing: "error",
  comma-spacing: ["error", { "before": false, "after": true }],
  space-before-function-paren: ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}],
  arrow-spacing: ["error", { "before": true, "after": true }],
  array-bracket-spacing: ["error", "never"],
  object-curly-spacing: ["error", "never"]
}